-- TBOP simple website: admin-only document publishing
-- Run this once in Supabase SQL Editor.

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.public_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Other',
  description text,
  file_name text not null,
  storage_path text not null unique,
  public_url text not null,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.site_admins enable row level security;
alter table public.public_documents enable row level security;

-- Public may read only published documents.
drop policy if exists "Public read published documents" on public.public_documents;
create policy "Public read published documents" on public.public_documents
for select to anon, authenticated
using (published = true or exists (select 1 from public.site_admins a where a.user_id = auth.uid()));

-- An authenticated user may check only whether THEIR OWN user ID is an admin.
drop policy if exists "Admins may verify themselves" on public.site_admins;
create policy "Admins may verify themselves" on public.site_admins
for select to authenticated
using (user_id = auth.uid());

-- Only listed admins may modify document metadata.
drop policy if exists "Admins insert documents" on public.public_documents;
create policy "Admins insert documents" on public.public_documents
for insert to authenticated
with check (exists (select 1 from public.site_admins a where a.user_id = auth.uid()));

drop policy if exists "Admins update documents" on public.public_documents;
create policy "Admins update documents" on public.public_documents
for update to authenticated
using (exists (select 1 from public.site_admins a where a.user_id = auth.uid()))
with check (exists (select 1 from public.site_admins a where a.user_id = auth.uid()));

drop policy if exists "Admins delete documents" on public.public_documents;
create policy "Admins delete documents" on public.public_documents
for delete to authenticated
using (exists (select 1 from public.site_admins a where a.user_id = auth.uid()));

-- Create the public storage bucket if it does not exist.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('club-documents','club-documents',true,20971520,array['application/pdf'])
on conflict (id) do update set public=true, file_size_limit=20971520, allowed_mime_types=array['application/pdf'];

-- Anyone can view files because the bucket is public; only admins can write/delete.
-- Authenticated admins may select their bucket object rows. This is also needed
-- for Storage upload responses that return the newly-created object metadata.
drop policy if exists "Admins select club documents" on storage.objects;
create policy "Admins select club documents" on storage.objects
for select to authenticated
using (bucket_id='club-documents' and exists (select 1 from public.site_admins a where a.user_id=auth.uid()));

drop policy if exists "Admins upload club documents" on storage.objects;
create policy "Admins upload club documents" on storage.objects
for insert to authenticated
with check (bucket_id='club-documents' and exists (select 1 from public.site_admins a where a.user_id=auth.uid()));

drop policy if exists "Admins update club documents" on storage.objects;
create policy "Admins update club documents" on storage.objects
for update to authenticated
using (bucket_id='club-documents' and exists (select 1 from public.site_admins a where a.user_id=auth.uid()))
with check (bucket_id='club-documents' and exists (select 1 from public.site_admins a where a.user_id=auth.uid()));

drop policy if exists "Admins delete club documents" on storage.objects;
create policy "Admins delete club documents" on storage.objects
for delete to authenticated
using (bucket_id='club-documents' and exists (select 1 from public.site_admins a where a.user_id=auth.uid()));

-- AFTER creating an admin user in Authentication > Users, add them like this:
-- insert into public.site_admins (user_id) values ('PASTE-THE-USER-UUID-HERE');
